#!/bin/sh
# ArmoryHub self-hosted installer.
#
#   curl -fsSL https://armoryhub.app/install.sh | sh
#
# What this does, in order:
#
#   1. Checks that Docker is installed and that you can use it
#   2. Creates ~/armoryhub and generates every password and secret for you
#   3. Downloads and starts ArmoryHub
#   4. Sets up HTTPS and prints a link for you to approve
#
# It does not need root, it asks you nothing, and it changes nothing outside
# ~/armoryhub. Re-running it on an existing install stops rather than overwriting.
#
# Set ARMORYHUB_DIR to install somewhere other than ~/armoryhub.
set -eu

REPO="${ARMORYHUB_CONFIG_REPO:-marcjwrigg/armoryhub-selfhost-install}"
RAW="https://raw.githubusercontent.com/${REPO}/main"
DIR="${ARMORYHUB_DIR:-$HOME/armoryhub}"

say()  { printf '%s\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()  { printf '\n  \033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

say ''
say 'ArmoryHub — self-hosted install'
say '================================'
say ''

# --- prerequisites -----------------------------------------------------------
command -v docker >/dev/null 2>&1 || die 'Docker is not installed. See https://docs.docker.com/engine/install/'
docker info >/dev/null 2>&1 || die 'Docker is installed but not usable by this user.
    Try:  sudo usermod -aG docker $USER   (then log out and back in)
    Or re-run this installer with sudo.'
docker compose version >/dev/null 2>&1 || die 'The Docker Compose plugin is missing.
    See https://docs.docker.com/compose/install/'
ok "docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo present)"

# Generates the passwords. Uses openssl where available, and the system random
# source otherwise, so this works on minimal server images too.
if command -v openssl >/dev/null 2>&1; then
  gen() { openssl rand -base64 "$1" | tr -d '\n/+=' | cut -c1-"$2"; }
else
  gen() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n' | cut -c1-"$2"; }
  warn 'openssl not found — using /dev/urandom for secrets'
fi

# --- location ----------------------------------------------------------------
if [ -e "$DIR/docker-compose.yml" ]; then
  die "$DIR already contains an install.

    To upgrade:  cd $DIR && docker compose pull && docker compose down && docker compose up -d

    Nothing has been changed. To install somewhere else, set ARMORYHUB_DIR:
      ARMORYHUB_DIR=~/armoryhub2 sh install.sh

    WARNING: do not 'rm -rf $DIR' to start over. Your database, photos and
    backups are inside it, under $DIR/data. Copy that directory somewhere safe
    first if you want to keep any of it."
fi
mkdir -p "$DIR"
cd "$DIR"
ok "install directory: $DIR"

# --- config ------------------------------------------------------------------
curl -fsSL "$RAW/docker-compose.yml" -o docker-compose.yml || die 'Could not download docker-compose.yml'
ok 'downloaded docker-compose.yml'

# Every value below is generated for you. Nothing here needs editing to get started,
# but you can change any of it later and restart with:
#   docker compose down && docker compose up -d
umask 077
cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file. Losing POSTGRES_PASSWORD locks the app out of its own database.

POSTGRES_PASSWORD=$(gen 32 32)
MIGRATOR_DB_PASSWORD=$(gen 32 32)
APP_DB_PASSWORD=$(gen 32 32)
AUTH_JWT_SECRET=$(gen 48 64)

APP_PORT=8477
APP_URL=http://localhost:8477
ALLOW_INSECURE_COOKIES=false

ENCRYPTION_AUTO_UNLOCK=false
STORAGE_DRIVER=fs
STORAGE_PATH=/data/files
REALTIME_MODE=poll
REALTIME_POLL_MS=30000
LICENSE_FILE=/data/license.jwt

BACKUP_HOUR=3
BACKUP_KEEP_DAILY=7
BACKUP_KEEP_WEEKLY=4

# --- HTTPS -------------------------------------------------------------------
# The installer starts Tailscale for you and prints a link to approve this machine.
# Nothing needs setting here.
#
# TS_AUTHKEY is only for UNATTENDED installs, where no one is present to click the
# approval link. Get a reusable, non-ephemeral key from
# https://login.tailscale.com/admin/settings/keys
# TS_AUTHKEY=
TS_HOSTNAME=armoryhub
EOF
chmod 600 .env
ok 'generated .env with unique secrets (mode 600)'

# --- data directories --------------------------------------------------------
# Creates the directories your data lives in, all under ./data:
#
#   data/postgres    the database
#   data/app/files   your photos and documents
#   data/backups     nightly backups
#
# These are ordinary directories rather than Docker volumes, so you can copy and
# back them up with whatever tools you already use, and `docker compose down -v`
# cannot delete them.
mkdir -p data/postgres data/app/files data/app/branding data/backups data/tailscale

# ArmoryHub runs as a different user inside the container, so it needs to own these
# directories to write to them. Your own account keeps read access via the group,
# which is what lets you copy your backups out without sudo.
#
# Done through a temporary container, so this needs no root access on your machine.
HOST_GID="$(id -g)"
if ! docker run --rm -v "$DIR/data:/d" alpine:latest \
      sh -c "chown -R 1001:${HOST_GID} /d/app /d/backups && chmod -R 750 /d/app /d/backups" >/dev/null 2>&1; then
  warn 'Could not set ownership on ./data/app and ./data/backups.'
  warn 'If the app or backups fail with permission errors, run:'
  warn "  docker run --rm -v $DIR/data:/d alpine sh -c 'chown -R 1001:${HOST_GID} /d/app /d/backups && chmod -R 750 /d/app /d/backups'"
fi
ok 'created ./data (postgres, app, backups, tailscale) — readable by you'

# --- start -------------------------------------------------------------------
say ''
say '  Pulling and starting (first run downloads ~150 MB)...'
docker compose pull --quiet 2>/dev/null || docker compose pull || die 'Could not pull the image'
docker compose up -d >/dev/null 2>&1 || die 'Failed to start. Inspect with:  cd '"$DIR"' && docker compose logs'
ok 'containers started'

# The containers start before the app is ready to use: it sets up its database and
# checks its configuration first. This waits for it to actually finish.
say ''
printf '  Waiting for first-time setup to finish'
i=0
while [ "$i" -lt 60 ]; do
  if curl -fsS -o /dev/null "http://localhost:8477/api/selfhost/auth/status" 2>/dev/null; then
    printf '\n'; ok 'ready'
    break
  fi
  printf '.'
  i=$((i + 1))
  sleep 3
done
if [ "$i" -ge 60 ]; then
  printf '\n'
  die "Did not become ready in time. See what happened:
    cd $DIR && docker compose logs app"
fi

# --- HTTPS -------------------------------------------------------------------
# Sets up HTTPS now rather than leaving it to you. This prints a link that you open
# to approve the machine — there is no key to create first.
#
# For an unattended install, put a reusable TS_AUTHKEY in .env before running and
# it registers without prompting.
say ''
say '  Setting up HTTPS...'
say ''
say '  This is required, not optional: browsers only allow the encryption ArmoryHub'
say '  needs over HTTPS or on localhost. Without it you can sign in but not unlock'
say '  your data.'
say ''

if ! docker compose --profile tailscale up -d >/dev/null 2>&1; then
  warn 'Could not start the Tailscale sidecar.'
  warn "Start it later with:  cd $DIR && docker compose --profile tailscale up -d"
  exit 0
fi
ok 'Tailscale sidecar started'

TS_CONTAINER=""
i=0
while [ "$i" -lt 20 ]; do
  TS_CONTAINER=$(docker compose ps -q tailscale 2>/dev/null || true)
  [ -n "$TS_CONTAINER" ] && break
  i=$((i + 1)); sleep 2
done

# Either an auth URL (no key) or successful registration (key present).
AUTH_URL=""
TS_NAME=""
printf '  Waiting for Tailscale'
i=0
while [ "$i" -lt 40 ]; do
  if [ -n "$TS_CONTAINER" ]; then
    AUTH_URL=$(docker logs "$TS_CONTAINER" 2>&1 | grep -oE 'https://login\.tailscale\.com/a/[a-z0-9]+' | tail -1 || true)
    TS_NAME=$(docker exec "$TS_CONTAINER" tailscale status --json 2>/dev/null \
      | tr ',' '\n' | grep -o '"DNSName":"[^"]*"' | head -1 | cut -d'"' -f4 | sed 's/\.$//' || true)
  fi
  [ -n "$AUTH_URL" ] && break
  [ -n "$TS_NAME" ] && break
  printf '.'
  i=$((i + 1)); sleep 3
done
printf '\n'

say ''
if [ -n "$TS_NAME" ]; then
  ok 'Tailscale registered automatically (auth key supplied)'
  say ''
  say '  ============================================================'
  say "   Open:  https://$TS_NAME"
  say '  ============================================================'
elif [ -n "$AUTH_URL" ]; then
  say '  ============================================================'
  say '   ONE STEP LEFT — approve this machine:'
  say ''
  say "     $AUTH_URL"
  say ''
  say '   Sign in, approve it, and your instance will be live at'
  say '   https://armoryhub.<your-tailnet>.ts.net'
  say '  ============================================================'
  say ''
  say '  The link is single-use. If it expires, get a fresh one with:'
  say "    cd $DIR && docker compose exec tailscale tailscale status"
else
  warn 'Tailscale did not report an auth URL in time.'
  say "  Check with:  cd $DIR && docker compose logs tailscale"
fi

say ''
say '  Create your account in the browser once HTTPS is up. You will set a'
say '  password (to sign in) and a PIN (to decrypt your data) — different things.'
say '  Your PIN cannot be recovered by anyone, so set up a recovery passphrase'
say '  immediately and write it down.'
say ''
say '  Useful commands:'
say "    cd $DIR"
say '    docker compose logs -f app                                    # what it is doing'
say '    docker compose --profile tools run --rm restore list          # backups'
say '    docker exec -it $(docker ps -q -f name=armoryhub.*app) node reset-password.js'
say ''
