#!/bin/sh
# ArmoryHub self-hosted installer.
#
#   curl -fsSL https://raw.githubusercontent.com/marcjwrigg/armoryhub-selfhost-install/main/install.sh | sh
#
# Generates every secret for you. Hand-editing an env file with four openssl
# invocations is the single biggest source of friction — and of weak or reused
# secrets — so it is automated rather than documented.
#
# POSIX sh, not bash: some minimal server images ship dash or busybox ash as
# /bin/sh, and an installer failing on the first line is a bad first impression.
set -eu

REPO="${ARMORYHUB_CONFIG_REPO:-marcjwrigg/armoryhub-selfhost-install}"
RAW="https://raw.githubusercontent.com/${REPO}/main"
DIR="${ARMORYHUB_DIR:-$HOME/armoryhub}"

say()  { printf '%s\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()  { printf '\n  \033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

say ''
say 'ArmoryHub — self-hosted install'
say '================================'
say ''

# --- prerequisites -----------------------------------------------------------
command -v docker >/dev/null 2>&1 || die 'Docker is not installed. See https://docs.docker.com/engine/install/'
docker info >/dev/null 2>&1 || die 'Docker is installed but not usable by this user.
    Try:  sudo usermod -aG docker $USER   (then log out and back in)
    Or re-run this installer with sudo.'
docker compose version >/dev/null 2>&1 || die 'The Docker Compose plugin is missing.
    See https://docs.docker.com/compose/install/'
ok "docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo present)"

# Secrets must be unguessable. Prefer openssl, fall back to /dev/urandom so this
# works on minimal images without it.
if command -v openssl >/dev/null 2>&1; then
  gen() { openssl rand -base64 "$1" | tr -d '\n/+=' | cut -c1-"$2"; }
else
  gen() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n' | cut -c1-"$2"; }
  warn 'openssl not found — using /dev/urandom for secrets'
fi

# --- location ----------------------------------------------------------------
if [ -e "$DIR/docker-compose.yml" ]; then
  die "$DIR already contains an install.
    To upgrade instead:   cd $DIR && docker compose pull && docker compose down && docker compose up -d
    To start over:        rm -rf $DIR   (this destroys nothing — data lives in Docker volumes)"
fi
mkdir -p "$DIR"
cd "$DIR"
ok "install directory: $DIR"

# --- config ------------------------------------------------------------------
curl -fsSL "$RAW/docker-compose.yml" -o docker-compose.yml || die 'Could not download docker-compose.yml'
ok 'downloaded docker-compose.yml'

# Written directly rather than downloading env.example and asking the operator to
# fill it in. Every value here is generated; nothing needs editing to get started.
umask 077
cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file. Losing POSTGRES_PASSWORD locks the app out of its own database.

POSTGRES_PASSWORD=$(gen 32 32)
MIGRATOR_DB_PASSWORD=$(gen 32 32)
APP_DB_PASSWORD=$(gen 32 32)
AUTH_JWT_SECRET=$(gen 48 64)

APP_PORT=8477
APP_URL=http://localhost:8477
ALLOW_INSECURE_COOKIES=false

ENCRYPTION_AUTO_UNLOCK=false
STORAGE_DRIVER=fs
STORAGE_PATH=/data/files
REALTIME_MODE=poll
REALTIME_POLL_MS=30000
LICENSE_FILE=/data/license.jwt

BACKUP_HOUR=3
BACKUP_KEEP_DAILY=7
BACKUP_KEEP_WEEKLY=4

# --- HTTPS (recommended) -----------------------------------------------------
# Browsers only permit the encryption ArmoryHub needs over HTTPS or on localhost,
# so reaching this by IP over plain http:// will let you sign in and then fail to
# unlock your data.
#
# Get a key at https://login.tailscale.com/admin/settings/keys (reusable,
# non-ephemeral), put it below, then:
#   docker compose --profile tailscale up -d
# TS_AUTHKEY=
TS_HOSTNAME=armoryhub
EOF
chmod 600 .env
ok 'generated .env with unique secrets (mode 600)'

# --- start -------------------------------------------------------------------
say ''
say '  Pulling and starting (first run downloads ~150 MB)...'
docker compose pull --quiet 2>/dev/null || docker compose pull || die 'Could not pull the image'
docker compose up -d >/dev/null 2>&1 || die 'Failed to start. Inspect with:  cd '"$DIR"' && docker compose logs'
ok 'containers started'

# The app applies the schema and validates its configuration before serving, so
# "up" is not the same as "ready".
say ''
printf '  Waiting for first-time setup to finish'
i=0
while [ "$i" -lt 60 ]; do
  if curl -fsS -o /dev/null "http://localhost:8477/api/selfhost/auth/status" 2>/dev/null; then
    printf '\n'; ok 'ready'
    break
  fi
  printf '.'
  i=$((i + 1))
  sleep 3
done
if [ "$i" -ge 60 ]; then
  printf '\n'
  die "Did not become ready in time. See what happened:
    cd $DIR && docker compose logs app"
fi

# --- next steps --------------------------------------------------------------
say ''
say '  Installed.'
say ''
say '  NEXT: set up HTTPS before creating your account.'
say '  Encryption cannot work over plain http:// except on localhost, so without'
say '  this you will be able to sign in but not unlock your data.'
say ''
say '    1. Get a Tailscale auth key (reusable, non-ephemeral):'
say '         https://login.tailscale.com/admin/settings/keys'
say "    2. Add it to $DIR/.env as   TS_AUTHKEY=tskey-auth-..."
say '    3. Then run:'
say "         cd $DIR && docker compose --profile tailscale up -d"
say ''
say '    That gives you https://armoryhub.<your-tailnet>.ts.net with a real'
say '    certificate, no port forwarding and no DNS setup.'
say ''
say '  Useful commands:'
say "    cd $DIR"
say '    docker compose logs -f app                                  # what it is doing'
say '    docker compose --profile tools run --rm restore list        # backups'
say '    docker exec -it $(docker ps -q -f name=armoryhub.*app) node reset-password.js'
say ''
