#!/bin/sh
# ArmoryHub self-hosted installer.
#
#   curl -fsSL https://armoryhub.app/install.sh | sh
#
# What this does, in order:
#
#   1. Checks that Docker is installed and that you can use it
#   2. Creates ~/armoryhub and generates every password and secret for you
#   3. Downloads and starts ArmoryHub
#   4. Sets up HTTPS and prints a link for you to approve
#
# It does not need root, it asks you nothing, and it changes nothing outside
# ~/armoryhub. Re-running it on an existing install stops rather than overwriting.
#
# Set ARMORYHUB_DIR to install somewhere other than ~/armoryhub.
#
# Set ARMORYHUB_TS_HOSTNAME to choose the name your instance gets on your private
# network, e.g. ARMORYHUB_TS_HOSTNAME=armory gives armory.<your-tailnet>.ts.net.
# Worth doing if you have reinstalled several times: certificates are rate-limited
# per hostname (5 per week), and a fresh name sidesteps a limit you have already hit.
set -eu

REPO="${ARMORYHUB_CONFIG_REPO:-marcjwrigg/armoryhub-selfhost-install}"
RAW="https://raw.githubusercontent.com/${REPO}/main"
DIR="${ARMORYHUB_DIR:-$HOME/armoryhub}"

say()  { printf '%s\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()  { printf '\n  \033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

say ''
say 'ArmoryHub — self-hosted install'
say '================================'
say ''

# --- prerequisites -----------------------------------------------------------
command -v docker >/dev/null 2>&1 || die 'Docker is not installed.

    On a fresh Debian or Ubuntu machine there is an optional script that sets
    up the system, Docker and your user groups in one go. It runs as root, so
    read it before you run it — it is a single short file:

      https://github.com/marcjwrigg/armoryhub-selfhost-install/blob/main/bootstrap-debian.sh

    Nothing here runs it for you. The instructions are in that page.

    Or install Docker yourself: https://docs.docker.com/engine/install/'
docker info >/dev/null 2>&1 || die 'Docker is installed but not usable by this user.
    Try:  sudo usermod -aG docker '"$(id -un)"'   (then log out and back in)

    The log out and back in is the part people miss — the group does not
    apply to a session that was already open.

    Or re-run this installer with sudo.'
docker compose version >/dev/null 2>&1 || die 'The Docker Compose plugin is missing.
    See https://docs.docker.com/compose/install/'
# Checked explicitly even though the advertised one-liner is itself curl-based: anyone
# who fetched this file with wget, scp or a browser gets here without curl, and the
# first thing to fail would be the compose download, reported as a network problem
# rather than as the missing tool it actually is. Debian ships without curl.
command -v curl >/dev/null 2>&1 || die 'curl is not installed, and this installer needs it.

    Debian does not include curl by default. Install it with:

      sudo apt-get update && sudo apt-get install -y curl'
ok "docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo present)"

# Generates the passwords. Uses openssl where available, and the system random
# source otherwise, so this works on minimal server images too.
if command -v openssl >/dev/null 2>&1; then
  gen() { openssl rand -base64 "$1" | tr -d '\n/+=' | cut -c1-"$2"; }
else
  gen() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n' | cut -c1-"$2"; }
  warn 'openssl not found — using /dev/urandom for secrets'
fi

# --- location ----------------------------------------------------------------
if [ -e "$DIR/docker-compose.yml" ]; then
  die "$DIR already contains an install.

    To upgrade:  cd $DIR && docker compose pull && docker compose down && docker compose up -d

    Nothing has been changed. To install somewhere else, set ARMORYHUB_DIR:
      ARMORYHUB_DIR=~/armoryhub2 sh install.sh

    WARNING: do not 'rm -rf $DIR' to start over. Your database, photos and
    backups are inside it, under $DIR/data. Copy that directory somewhere safe
    first if you want to keep any of it."
fi
mkdir -p "$DIR"
cd "$DIR"
ok "install directory: $DIR"

# --- config ------------------------------------------------------------------
curl -fsSL "$RAW/docker-compose.yml" -o docker-compose.yml || die 'Could not download docker-compose.yml'
ok 'downloaded docker-compose.yml'

# Every value below is generated for you. Nothing here needs editing to get started,
# but you can change any of it later and restart with:
#   docker compose down && docker compose up -d
umask 077
cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file. Losing POSTGRES_PASSWORD locks the app out of its own database.

POSTGRES_PASSWORD=$(gen 32 32)
MIGRATOR_DB_PASSWORD=$(gen 32 32)
APP_DB_PASSWORD=$(gen 32 32)
AUTH_JWT_SECRET=$(gen 48 64)

APP_PORT=8477
APP_URL=http://localhost:8477
ALLOW_INSECURE_COOKIES=false

REALTIME_POLL_MS=30000

BACKUP_HOUR=3
BACKUP_KEEP_DAILY=7
BACKUP_KEEP_WEEKLY=4

# Keeps the Tailscale sidecar in every future 'docker compose up -d'.
#
# Without this, Tailscale only starts when you remember --profile tailscale. Once it
# has been stopped for any reason, a plain 'up -d' leaves it down and your HTTPS
# address quietly stops resolving, which looks like the app itself being broken.
#
# Change this to 'caddy' if you switch to a public domain instead.
COMPOSE_PROFILES=tailscale

# --- HTTPS -------------------------------------------------------------------
# The installer starts Tailscale for you and prints a link to approve this machine.
# Nothing needs setting here.
#
# TS_AUTHKEY is only for UNATTENDED installs, where no one is present to click the
# approval link. Get a reusable, non-ephemeral key from
# https://login.tailscale.com/admin/settings/keys
# TS_AUTHKEY=
TS_HOSTNAME=${ARMORYHUB_TS_HOSTNAME:-armoryhub}
EOF
chmod 600 .env
ok 'generated .env with unique secrets (mode 600)'

# --- data directories --------------------------------------------------------
# Creates the directories your data lives in, all under ./data:
#
#   data/postgres    the database
#   data/app/files   your photos and documents
#   data/backups     nightly backups
#
# These are ordinary directories rather than Docker volumes, so you can copy and
# back them up with whatever tools you already use, and `docker compose down -v`
# cannot delete them.
mkdir -p data/postgres data/app/files data/backups data/tailscale

# ArmoryHub runs as a different user inside the container, so it needs to own these
# directories to write to them. Your own account keeps read access via the group,
# which is what lets you copy your backups out without sudo.
#
# Done through a temporary container, so this needs no root access on your machine.
HOST_GID="$(id -g)"
if ! docker run --rm -v "$DIR/data:/d" alpine:latest \
      sh -c "chown -R 1001:${HOST_GID} /d/app /d/backups && chmod -R 750 /d/app /d/backups" >/dev/null 2>&1; then
  warn 'Could not set ownership on ./data/app and ./data/backups.'
  warn 'If the app or backups fail with permission errors, run:'
  warn "  docker run --rm -v $DIR/data:/d alpine sh -c 'chown -R 1001:${HOST_GID} /d/app /d/backups && chmod -R 750 /d/app /d/backups'"
fi
ok 'created ./data (postgres, app, backups, tailscale) — readable by you'

# --- management helper --------------------------------------------------------
# Everything the operator needs afterwards goes through this rather than through
# `docker compose`, because dashboards that rewrite the compose file strip the
# profile-gated services and break those commands. The helper reads Docker directly.
curl -fsSL "$RAW/armoryhub" -o armoryhub 2>/dev/null && chmod +x armoryhub || warn 'could not download the armoryhub helper'
if [ -f armoryhub ]; then
  # Only the no-prompt paths here. If neither works we ask at the end, once the
  # install has succeeded, rather than interrupting it for a password.
  if [ -w /usr/local/bin ] && install -m 755 armoryhub /usr/local/bin/armoryhub 2>/dev/null; then
    ok 'installed the `armoryhub` command'
  elif sudo -n install -m 755 armoryhub /usr/local/bin/armoryhub 2>/dev/null; then
    ok 'installed the `armoryhub` command'
  else
    ok "management helper saved to $DIR/armoryhub"
  fi
fi

# --- start -------------------------------------------------------------------
say ''
say '  Pulling and starting (first run downloads ~150 MB)...'
docker compose pull --quiet 2>/dev/null || docker compose pull || die 'Could not pull the image'
docker compose up -d >/dev/null 2>&1 || die 'Failed to start. Inspect with:  cd '"$DIR"' && docker compose logs'
ok 'containers started'

# The containers start before the app is ready to use: it sets up its database and
# checks its configuration first. This waits for it to actually finish.
say ''
printf '  Waiting for first-time setup to finish'
i=0
while [ "$i" -lt 60 ]; do
  if curl -fsS -o /dev/null "http://localhost:8477/api/selfhost/auth/status" 2>/dev/null; then
    printf '\n'; ok 'ready'
    break
  fi
  printf '.'
  i=$((i + 1))
  sleep 3
done
if [ "$i" -ge 60 ]; then
  printf '\n'
  die "Did not become ready in time. See what happened:
    cd $DIR && docker compose logs app"
fi

# --- HTTPS -------------------------------------------------------------------
# Sets up HTTPS now rather than leaving it to you. This prints a link that you open
# to approve the machine — there is no key to create first.
#
# For an unattended install, put a reusable TS_AUTHKEY in .env before running and
# it registers without prompting.
say ''
say '  Setting up HTTPS...'
say ''
say '  This is required, not optional: browsers only allow the encryption ArmoryHub'
say '  needs over HTTPS or on localhost. Without it you can sign in but not unlock'
say '  your data.'
say ''

if ! docker compose --profile tailscale up -d >/dev/null 2>&1; then
  warn 'Could not start the Tailscale sidecar.'
  warn "Start it later with:  cd $DIR && docker compose --profile tailscale up -d"
  exit 0
fi
ok 'Tailscale sidecar started'

TS_CONTAINER=""
i=0
while [ "$i" -lt 20 ]; do
  TS_CONTAINER=$(docker compose ps -q tailscale 2>/dev/null || true)
  [ -n "$TS_CONTAINER" ] && break
  i=$((i + 1)); sleep 2
done

# Approving the machine is a race, and the installer has to run it rather than hope.
#
# While a node sits unauthenticated, the tailscale container re-registers itself about
# once a minute (measured on a test machine: five regenerations, ~60s apart). Every
# re-registration mints a new node key and a NEW approval link, silently invalidating
# the one already on screen. Anyone who reads the message, then goes to find their
# password manager, misses the window — and the symptom is an approval link that
# simply does nothing, followed by a node in the admin console whose "last seen"
# equals its creation time.
#
# So: print the link, watch for it to change, and reprint it when it does.

ts_field() {
  [ -n "$TS_CONTAINER" ] || return 1
  docker exec "$TS_CONTAINER" tailscale status --json 2>/dev/null \
    | grep -m1 "\"$1\"" | cut -d'"' -f4
}

APPROVE_WINDOW=75   # the link lives ~60s; allow a buffer before assuming it rotated
APPROVE_ROUNDS=5    # give up after ~6 minutes and explain the auth-key path
TS_NAME=""
LAST_URL=""
round=1

say ''
while [ "$round" -le "$APPROVE_ROUNDS" ]; do
  STATE=$(ts_field BackendState || true)

  if [ "$STATE" = "Running" ]; then
    TS_NAME=$(ts_field DNSName | sed 's/\.$//' || true)
    break
  fi

  URL=$(ts_field AuthURL || true)
  if [ -n "$URL" ] && [ "$URL" != "$LAST_URL" ]; then
    LAST_URL="$URL"
    say '  ============================================================'
    if [ "$round" -eq 1 ]; then
      say '   ONE STEP LEFT — approve this machine:'
    else
      say "   That link expired. Here is a fresh one (attempt $round):"
    fi
    say ''
    say "     $URL"
    say ''
    say '   This link is only valid for about a minute. If you miss it, leave this'
    say '   running — a new one is printed automatically.'
    say '  ============================================================'
  fi

  # Poll inside the window so approval is noticed within seconds, not at the end.
  waited=0
  while [ "$waited" -lt "$APPROVE_WINDOW" ]; do
    sleep 5
    waited=$((waited + 5))
    if [ "$(ts_field BackendState || true)" = "Running" ]; then break; fi
  done

  round=$((round + 1))
done

say ''
if [ -n "$TS_NAME" ]; then
  ok "Tailscale approved: $TS_NAME"

  # Point the dashboard app-card icon at this instance now that we know its address.
  #
  # The published compose file ships the icon embedded as a data: URI, because at
  # publish time nobody knows what this machine will be called. That always works but
  # is only 96px. Now that Tailscale has registered we know the real hostname, so we
  # can point at the full-size icon the app already serves — still entirely on your own
  # network, still no third-party fetch.
  #
  # Only swapped when Tailscale is in use. Anyone behind their own reverse proxy keeps
  # the embedded copy, which needs no address at all.
  #
  # sed to a temp file and rename, rather than sed -i: -i is a GNU/BSD extension and
  # its argument handling differs between them.
  if grep -q '^  icon: data:image/png' docker-compose.yml 2>/dev/null; then
    if sed "s|^  icon: data:image/png.*|  icon: https://$TS_NAME/apple-touch-icon.png|" \
         docker-compose.yml > docker-compose.yml.tmp 2>/dev/null \
       && mv docker-compose.yml.tmp docker-compose.yml; then
      ok "app icon set to https://$TS_NAME/apple-touch-icon.png"
    else
      rm -f docker-compose.yml.tmp
    fi
  fi
else
  warn 'The machine was not approved in time.'
  say ''
  say '  Nothing is broken — the app is running, it just has no HTTPS address yet.'
  say '  Get the current link any time with:'
  say "    docker exec \$(docker ps -q -f name=tailscale) tailscale status"
  say ''
  say '  If you keep missing the window, use an auth key instead. It authenticates'
  say '  on boot, so there is no link and no timing to get right:'
  say ''
  say '    1. Create a REUSABLE, non-ephemeral key at'
  say '       https://login.tailscale.com/admin/settings/keys'
  say "    2. echo 'TS_AUTHKEY=tskey-auth-...' >> $DIR/.env"
  say "    3. cd $DIR && docker rm -f \$(docker ps -q -f name=tailscale) && docker compose up -d"
fi

# Wait for the certificate, and say what went wrong if it does not arrive.
#
# Without this the installer prints a URL and exits, and any certificate failure
# reaches the operator as a blank page with an empty browser console — no error, no
# clue, and nothing that points at TLS. That is the single worst failure mode this
# script has, because everything else looks healthy: containers up, app answering on
# loopback, Tailscale connected.
#
# Certificates are issued on demand, on the first HTTPS request, so this makes that
# request rather than waiting to be surprised later.
if [ -n "$TS_CONTAINER" ]; then
  say ''
  printf '  Waiting for the HTTPS certificate'
  CERT_OK=""
  i=0
  while [ "$i" -lt 30 ]; do
    NAME=$(docker exec "$TS_CONTAINER" tailscale status --json 2>/dev/null \
      | grep -m1 '"DNSName"' | cut -d'"' -f4 | sed 's/\.$//' || true)
    if [ -n "$NAME" ] && docker exec "$TS_CONTAINER" \
         wget -q -T 8 -O /dev/null "https://$NAME/api/selfhost/auth/status" 2>/dev/null; then
      CERT_OK=yes
      break
    fi
    printf '.'
    i=$((i + 1)); sleep 4
  done
  printf '\n'

  if [ -n "$CERT_OK" ]; then
    ok "HTTPS working: https://$NAME"
    say ''
    say '  ============================================================'
    say "   Open:  https://$NAME"
    say '  ============================================================'
  else
    # Distinguish "not approved yet" from a real certificate failure, because the
    # remedies are completely different.
    RATE=$(docker logs "$TS_CONTAINER" 2>&1 | grep -oE 'too many certificates.*retry after [0-9: -]+UTC' | tail -1 || true)

    # Distinguish a TLS problem from a proxy problem. If the certificate itself is
    # fine, HTTPS is working and the fault is between Tailscale and the app — usually
    # just the app still starting, which returns 502 for a few seconds.
    CERT_FINE=""
    if [ -n "$NAME" ] && docker exec "$TS_CONTAINER" \
         tailscale cert --cert-file /tmp/_c --key-file /tmp/_k "$NAME" >/dev/null 2>&1; then
      CERT_FINE=yes
    fi

    say ''
    if [ -n "$CERT_FINE" ] && [ -z "$RATE" ]; then
      ok "Certificate is valid for $NAME"
      warn 'But the app did not answer through it yet.'
      say ''
      say '  Almost always the app still finishing its first start. Wait a few seconds'
      say "  and open:  https://$NAME"
      say ''
      say '  If it keeps returning 502:'
      say "    cd $DIR && docker compose logs app"
    elif [ -n "$RATE" ]; then
      warn 'HTTPS is blocked by a Let'"'"'s Encrypt rate limit.'
      say ''
      say "    $RATE"
      say ''
      say '  Five certificates have already been issued for this exact hostname in the'
      say '  last 7 days, which happens after repeated reinstalls. The limit is per'
      say '  hostname, so you have two options:'
      say ''
      say '    1. Wait until the time above, then:  docker compose up -d'
      say '    2. Use a different name now:'
      say "         cd $DIR"
      say '         sed -i "s|^TS_HOSTNAME=.*|TS_HOSTNAME=armory2|" .env'
      say '         sed -i "s|^APP_URL=.*|APP_URL=https://armory2.<your-tailnet>.ts.net|" .env'
      say '         docker compose up -d --force-recreate tailscale'
      say ''
      say '  Until then the app is running but only reachable at'
      say "  http://localhost:${APP_PORT:-8477} from this machine."
    elif [ -n "$AUTH_URL" ]; then
      say '  Not approved yet — that is expected if you have not opened the link above.'
      say '  Once you approve the machine, HTTPS starts working within a few seconds.'
      say ''
      say '  If it does not, check for a certificate error with:'
      say "    cd $DIR && docker compose logs tailscale | grep -i cert"
    else
      warn 'HTTPS did not come up, and no certificate error was reported.'
      say "  Check:  cd $DIR && docker compose logs tailscale"
    fi
  fi
fi

say ''
say '  Create your account in the browser once HTTPS is up. You will set a password'
say '  (to sign in) and a PIN (to decrypt your data) — different things. The password'
say '  can be reset from this server. The PIN CANNOT, by anyone, including us.'
say ''
say '  Write your PIN down and keep it somewhere safe and offline.'
say ''
say '  A passphrase is optional. It gives the copy of your key held on this server'
say '  much stronger protection than a 6-digit PIN can. If you set one, it is also'
say '  required — together with your PIN — to set up any other device, so write both'
say '  down. Neither can be recovered if you lose them.'
say ''
# Point people at the helper rather than at raw compose commands. Compose commands
# with --profile break the moment a dashboard rewrites docker-compose.yml, and the
# helper does not read that file at all.
if [ -x /usr/local/bin/armoryhub ]; then
  AH='armoryhub'
else
  AH="$DIR/armoryhub"
fi

# Offer to put the helper on PATH, now that everything else has worked.
#
# read must come from /dev/tty, not stdin. The documented install is
# `curl ... | sh`, which means stdin IS the script — a bare `read` would consume the
# next lines of the installer instead of waiting for the operator, and the rest of the
# script would silently vanish. If there is no tty at all (unattended install), skip
# the question rather than hanging forever.
# Probe the terminal by opening it, rather than testing [ -r /dev/tty ]. The file can
# exist and pass that test while still being unusable when the script is piped, which
# prints "Device not configured" after the question is already on screen.
TTY_OK=""
if { exec 3</dev/tty; } 2>/dev/null; then TTY_OK=yes; fi

if [ -f "$DIR/armoryhub" ] && [ ! -x /usr/local/bin/armoryhub ] && [ -n "$TTY_OK" ]; then
  say ''
  printf '  Install the `armoryhub` command to /usr/local/bin? Needs sudo. [Y/n] '
  ANS=''
  read -r ANS <&3 || ANS=n
  case "$ANS" in
    ''|y|Y|yes|YES|Yes)
      if sudo install -m 755 "$DIR/armoryhub" /usr/local/bin/armoryhub </dev/tty; then
        ok 'installed — run `armoryhub doctor` from anywhere'
      else
        warn "not installed; run it as $DIR/armoryhub"
      fi ;;
    *)
      say "  Skipped. Run it as $DIR/armoryhub, or later:"
      say "    sudo install -m 755 $DIR/armoryhub /usr/local/bin/armoryhub" ;;
  esac
  say ''
elif [ -f "$DIR/armoryhub" ] && [ ! -x /usr/local/bin/armoryhub ]; then
  say ''
  say '  To run `armoryhub` from anywhere:'
  say "    sudo install -m 755 $DIR/armoryhub /usr/local/bin/armoryhub"
  say ''
fi

say '  Useful commands:'
say "    $AH doctor          # check everything and say what is wrong"
say "    $AH logs            # what the app is doing"
say "    $AH url             # the address to open"
say "    $AH backup list     # your backups"
say "    $AH password        # reset your account password"
say ''
if [ ! -x /usr/local/bin/armoryhub ] && [ -f "$DIR/armoryhub" ]; then
  say '  To run it as just `armoryhub` from anywhere:'
  say "    sudo install -m 755 $DIR/armoryhub /usr/local/bin/armoryhub"
  say ''
fi
